logFormat: "[request] [status] [time]"
max_thread: 3310

server:
    server_name: "localhost"
    listen: 8080
    max_client_body_size: 1000

    location:
        path: /static
        root: /var/www/static
        index: index.html

    location:
        path: /images
        root: /var/www/images
        index: index.jpg
