server1:
    server_name: "MyServer1"
    listen: 8080
    max_client_body_size: 4096
    max_client_header_size: 1024
    keep_alive: 30

    location:
        path: "/"
        root: "/myserver1/"
        methods: "GET"
    
    errors:
        500: "500.html"
        404: "404.html"

server2:
    server_name: "MyServer2"
    listen: 8081
    max_client_body_size: 256
    max_client_header_size: 512
    keep_alive: 5

    location:
        path: "/"
        root: "/myserver2/"
        index: "index.html"
        methods: "GET"
    
    location:
        path: "/secret"
        root: "/myserver2/"
        index: "hidden.html"

    errors:
        500: "500.html"
        404: "404.html"

server3:
    server_name: "MyServer3"
    listen: 8082
    max_client_body_size: 16384
    max_client_header_size: 2048
    keep_alive: 1

    location:
        path: "/"
        root: "/myserver3/src/"
        index: "index.html"
        methods: "GET"

    location:
        path: "/cgi"
        root: "/myserver3/cgi/"
        index: "index.py"
        methods: "POST DELETE"
        exact: true
        cgi: true
    
    errors:
        500: "500.html"
        404: "404.html"